image: node:boron
before_script:
  - npm install
cache:
  paths:
    - node_modules/

stages:
  - test
  - build
  - publish

build:
  stage: build
  script:
    - npm run code-check
    - npm run cover
    - node node_modules/grunt-cli/bin/grunt build

publish:
  stage: publish
  only:
    - master
  script:
    - node node_modules/grunt-cli/bin/grunt publish