language: node_js
node_js:
- '6'
install:
- npm install
script:
- npm run code-check
- npm run cover
- grunt build
before_deploy:
- cd dist
deploy:
  provider: npm
  skip_cleanup: true
  email: TrdelnikSquad@cimpress.com
  api_key:
    secure: kwXE5TBOmX1yx5bz2HXpbCen7rf26Vd3O1fKfY9FFXEAFfzL+ssxEQ5729IHr9QSki3Gcj1LDSRkBj8u4O2kLz2VNE1XOIfAlwasaHomVQ60B1zu/Gg6/9wqt/Fj72NGI4/ofh5pOaB+2Ypsl+66NkrcKAbv58ZxfFZgReKVNHEhYyDFL4XeNmp9hE3IfNl7vwj0QKz1yvZyWsA9zH2HA2++rH9LqtysZWqikROYahu2C0pKyUwmB1dp+bXZfhGRgZ3qKBWrapSjNRQDAmC09UZIxBzhmDQVtwIORcssxbGXsBaSZkDtLMvQ8F36CEydcI0MRvBrmsX8WruErrXe0EofqzqbotlqFaYZHUkRGWTZC//kvwtNAyosS+76JPAsLgjw1fxZ+TKTRMP9JjNpvUvl7SvTws4BknAp3aSS5bMtOTOMXD4GSXQwNL9nquvwzr8QTv/H7NCPSXraqZcMhbn+ZxPxHqVZXqATQospNzekABTvfoSvGbxRvmEmOqNkt7TGuQGga2rA9zbXEG/xBea2+KW4b25m+jT3J6EFts+VxUWenYFAXvfQC7wwELTh5Qj7vp1jrwu+ryi29gX+1B/xc4LmO/6cG52o7ScDLD07y7trFbhx4ZDABTBuZR/+Me0rUDtAQLPw1dfMwdBJs8FqW8JrrCh1ek7NggrmW/A=
  on:
    branch: master
