language: node_js
node_js:
- '6'
install:
- npm install
script:
- npm run code-check
- npm run cover
- grunt build
before_deploy:
- cd dist
deploy:
  provider: npm
  skip_cleanup: true
  email: TrdelnikSquad@cimpress.com
  api_key:
    secure: QGy0v86bA8dGjCxfON5aVlBTfRgl4Okkbvflnp23xgUaqPtfXWmUu6cT9o3jSy/WAHfNV6u8cRw6kr98yVfrRQ9MANPAmMpTZPHMN9G23yJJgSuVSKJFWnwiXfXdVEPaQg6CstObQdQw/Hnf576KU5Z/ES9tGZwmsna21HbhyBR9CCpOPuRJVeV6d1gSCO/W/Q6/duzLU8WQ2jzLgxcGutNacukGqCNFzB1lGP9pInJ2OSdlE701khSLU1c/SBts6K/EUkZWQr9avwl0KlPOQ9HylZwW5Wmu8O9D0JBdlutEL8hxDdB1JX17LaAu/4LyKtcuQGNAacM5Nm6ikVjDKZ6tB5PjCZ6WKxxnAn8+LCZK9kZcKOJ0hv/rWI4Erb/gyKfIqsJ1AorcPHP9j11whulVkNm4/BuutkGD+RS5qdML9ktpF3UkUDJbVtbkRB5ejGIPnw2VHsU2ccTpZD/glRq+tQca9L076WKuMRJ4ETkm71wZISabek7VUApiW3MbbVHwQWyVfJSwrobEWvFmtnZW1UTNSrWZBJixyxTttSlPB/3Y1hEY02BNcYpBHZVPxPWrh8hd6mHkmU55hri/uT70IVg0gxpUsaD4HwBSGTLH56sqokHPm+OOurgYqKnKUl6xq3o0BwJn8kbbiKQjC86WglgwwtHYEzVUeJ0DY/c=
  on:
    branch: master
