language: node_js
node_js:
- '6'
install:
- npm install
script:
- npm run code-check
- npm run cover
- grunt build
deploy:
  provider: npm
  skip_cleanup: true
  email: indirapranabudi@gmail.com
  api_key:
    secure: odI8A7gKwdZCkj2oVhbZAO4V9NRGKAxnYcznfok06a9RWRPrFB4umR0DT831Ij/u8QsUly0mycSA31QhJu695M3RkEjEDGaXA3Q/PBeHdIr/lz0m1qdYUIuF0VXuRNiRE2El9vm4Idst3VDGjG8LwF1ulODxD0RdGzxqlAzbPobStd3r78dOv1FgIJkdslivUe2fk0aSkUXKxCAP/KCef0AxKsPPdRuvMBQTwli+/sFZaPUESBMf+EBf6+AbbywxgtqHgi8xZj3yaJ8Jm+iA/vqDl1CGHklIbpLglQMuKfWuYQlqySpE+M4m+J6/uOUoEh17I/C0SGlrWtJnwhPc/YVsHWs1YG5wEGzfv7n/DY+HNp3j78PMACbgHlkTgiKKRZ6RLKjNps1s8CR/iMVFBHGuyBZQnSFBCj9PRM7SPLG/IXZ6EfkzIRaIMCOMYjslt+lHpsifogDySsKKCkoXzZJ6m2+g9wM7MNhLPOpRg3HQk4ZVliU2conWqrzsqWClrobkoWniDpkjCPRVdgZKcGGcGeVAmhcqrSREeoJxhzBi7gPk1gHyZlxPqggKZDGjI2D7+uLMexEewSdFmlFe2Zkjx6wAI3MKMWaSJRaPaSii9IQF97f+2GRuiVWz8XuIkPuE/ugvU0wSyXoCyhqi19JBadRrBl41FmLNYvCkdl0=
  on:
    branch: master