language: node_js
node_js:
- '12'
install:
- npm install
script:
- npm run code-check
- npm run cover
- grunt build
before_deploy:
- cd dist
deploy:
  provider: npm
  skip_cleanup: true
  email: TrdelnikSquad@cimpress.com
  api_key:
    secure: 7UcFoiS44RCveYyEbDw90wokJj8lM00XegLF+0PoUcoQAdLs2b9at7zQBmgZZryNNmENv44cROHG1mtxn5x6FOBDWyEp95Hlh61yS+2dSfhJzl4/MMemi60Ecs+iGOr//r7XVQpaIbeCKwm2fuH0nbBxQhVD/wzFPqRDQrJjJF8+s0neQhiuGZq7wt8tyflj2FsJC5ntAf7gcd1aseGOK8pENIaV2yuEbhJtpzRbs2+psiLVdMhtxHuaKzuQ0gXa5CzCiT5JJq8cidBNQuc29eM7UT61c46HXEWDVLPOsBB7gqJ1v6pLtFlxyjpJBDYiZK3pHHc42evVEl1Gma7ylhqBGVtedkReadlwPuTnpM+SrNk4LKXNvu0LJM4B/mffvB4E7NnBMTJfn0GpEay24VuSNpzaTlb7vuwlaKRXOnITOCKfXfZB2ggn3DJ9gjKHoYKvb2Jd9J+8IpkziJhRVBECErCUk0fI32yHB/BmQNvXZlgosPmLceGiHOFglAXM2AyrJaoHIr4VspliisVPqK4vDy0vs6PGnePmuJIEwZRNp8t6JjZflMds8omOfjWAwGih50xKwlCa2AAuUca3y9cgJfzaybhdq5IPKK0aHSbRNcDbml/REJf56DXLE4JWP3zm44K0sNxKHGkUexfjXyHbL2+rQa46ld9aSwpoE2k=
  on:
    branch: master
