language: node_js
node_js:
- '6'
install:
- npm install
script:
- npm run code-check
- npm run cover
- grunt build
before_deploy:
- cd dist
deploy:
  provider: npm
  skip_cleanup: true
  email: indirapranabudi@gmail.com
  api_key:
    secure: 4h5zUn8mrAonSSjGhPaqLTpY6em2qLW18dPXyRFcIvTewdCQhlLJES5RZcMn0QrG42f8F6d5MJ7SicFpLA4oPj1fdtOqIUT87+iCaFXtVXYxyppWVNL6Qknh8KOAKjxw1SRrsPkdXNfSOrXiLpXoza9iwBqaR2UVYsxCT3T+wS7b2jYyCKyC6YWgK90BLzq4MSXeomL7RZCsgMtveEc8BYhFRrjneO4TJfDAzn/wo0rz/SxJZkQ1inUJcTXEGv6ATIH3ivgzvN0GrZWedwC4xio05Ve9jD0gYvUL7fxaJuIAv4xbdJyzdFw8LrJ0BUYakqiuY7GbIhHStNGdAvQdIw0xSrRsL8dj2KRbgj/7GYV1I2HMN4slMcbiydY0MuTri2Oie7gRZPRyUJkSZcm4bB5ITfNvN/q16Zcu32fQH93iW96Yk1kH73ykZV47Sd5wXVKcxz+kVdQd2vdCa9R/L4s0/+k1jmS36F1fzi08oGjyOGFQNdqzuhi79sgAG+X+0fiMvt9PqNBqa6eYTlyIsD4Xz5F3Oen++G6fTRKdruC/pwcbiguqW0G9kO1YhOsXJx5v/djYa6FAEmdQhbL84mSK+I0+/pdn5cckhSj1GXqiyQ8n8Yqb4CaBUXSJFfrmPc5T4g26MfUU2vyITqQ/ej6V7YPqN8ZkBMmXQXl+Dls=
  on:
    branch: master